"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Search, Save } from "lucide-react";
import { useDemo } from "./demo-provider";
import { PageHeading, EmptyState } from "./shell";
import { ProfileDetails, SavedSetTable } from "./patient-views";
import { exercises, ageOn, sexLabel, strokeLabel, dateLabel } from "@/lib/demo-data";

export function DoctorDashboard() {
  const { profiles, sets } = useDemo(); const [query, setQuery] = useState(""); const [perPage, setPerPage] = useState(5); const [page, setPage] = useState(1);
  const filtered = profiles.filter(p => `${p.full_name} ${p.hn}`.toLowerCase().includes(query.toLowerCase())); const maxPage = Math.max(1, Math.ceil(filtered.length / perPage));
  return <><PageHeading title="รายชื่อผู้ป่วย" subtitle={`${profiles.length} รายในข้อมูลตัวอย่าง`} /><div className="filter-bar"><label><span><Search size={16} className="inline" /> ค้นหาผู้ป่วย</span><input value={query} onChange={e => { setQuery(e.target.value); setPage(1); }} placeholder="ชื่อ - นามสกุล หรือ HN" /></label><label>รายชื่อต่อหน้า<select value={perPage} onChange={e => { setPerPage(Number(e.target.value)); setPage(1); }}><option value={5}>5</option><option value={10}>10</option><option value={20}>20</option></select></label></div><div className="patient-list">{filtered.slice((page - 1) * perPage, page * perPage).map(p => <article className="patient-row" key={p.id}><span className="tag">{p.hn}</span><div><h2>{p.full_name}</h2><p>{ageOn(p.date_of_birth)} · {sexLabel[p.sex]}</p></div><span className="muted">{sets.filter(s => s.patient_id === p.id).length} เซตที่บันทึก</span><Link className="command" href={`/doctor/patients/${p.id}`}>ตรวจสอบ <ArrowRight size={18} /></Link></article>)}</div>{!filtered.length && <EmptyState title="ไม่พบผู้ป่วยที่ค้นหา" />}<div className="action-row"><button className="command" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>ก่อนหน้า</button><span>หน้า {page} / {maxPage}</span><button className="command" disabled={page >= maxPage} onClick={() => setPage(p => p + 1)}>ถัดไป</button></div></>;
}
export function PatientTabs({ patientId, active }: { patientId: string; active: "profile" | "history" | "plan" }) {
  return <nav className="tabs" aria-label="ข้อมูลผู้ป่วย"><Link href={`/doctor/patients/${patientId}`} aria-current={active === "profile" ? "page" : undefined}>ข้อมูลผู้ป่วย</Link><Link href={`/doctor/patients/${patientId}/assessments`} aria-current={active === "history" ? "page" : undefined}>ประวัติการฝึก</Link><Link href={`/doctor/patients/${patientId}/plan`} aria-current={active === "plan" ? "page" : undefined}>แผนฝึก</Link></nav>;
}
export function DoctorPatient({ id }: { id: string }) {
  const { profiles, plans, setProfiles } = useDemo(); const p = profiles.find(p => p.id === id)!; const [notes, setNotes] = useState(p.medical_notes); const [saved, setSaved] = useState(false);
  return <><PageHeading title={p.full_name} subtitle={p.hn} back="/doctor" /><PatientTabs patientId={id} active="profile" /><div className="split-view"><section><h2>ข้อมูลพื้นฐาน</h2><ProfileDetails profile={p} /></section><section><h2>ข้อมูลสุขภาพ</h2><dl className="data-list"><div><dt>ประเภทโรค</dt><dd>{strokeLabel[p.stroke_type]}</dd></div><div><dt>วันที่วินิจฉัย</dt><dd>{dateLabel(p.stroke_diagnosed_on)}</dd></div><div><dt>โรคประจำตัวอื่น</dt><dd>{p.other_conditions || "ไม่ระบุ"}</dd></div></dl><form className="form-stack" onSubmit={e => { e.preventDefault(); setProfiles(current => current.map(profile => profile.id === id ? { ...profile, medical_notes: notes } : profile)); setSaved(true); }}><label htmlFor="medical-notes">บันทึกทางการแพทย์</label><textarea id="medical-notes" value={notes} onChange={e => { setNotes(e.target.value); setSaved(false); }} /><div className="action-row"><button className="command"><Save size={18} />บันทึกหมายเหตุ</button></div>{saved && <p role="status" className="notice">ปรับบันทึกตัวอย่างแล้ว</p>}</form></section></div><div className="section-heading"><h2>แผนฝึกปัจจุบัน</h2><Link className="command" href={`/doctor/patients/${id}/plan`}>ปรับแผน</Link></div><div className="exercise-grid">{(plans[id] || []).map(item => <article className="exercise-item" key={item.exercise_id}><h2>{exercises.find(e => e.id === item.exercise_id)!.name}</h2><p>{item.target_sets} เซต × {item.target_reps_per_set} ครั้ง</p><p>{item.schedule_type === "daily" ? "ทุกวัน" : `วันในสัปดาห์: ${item.weekdays.join(", ")}`}</p></article>)}</div>{!plans[id]?.length && <EmptyState title="ยังไม่มีแผนฝึก" />}</>;
}
export function DoctorHistory({ id }: { id: string }) {
  const { profiles } = useDemo(); const [date, setDate] = useState(""); const p = profiles.find(p => p.id === id)!;
  return <><PageHeading title="ประวัติการฝึก" subtitle={`${p.full_name} · ${p.hn}`} back={`/doctor/patients/${id}`} /><PatientTabs patientId={id} active="history" /><div className="filter-bar"><label>วันที่ฝึก<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><button className="command" onClick={() => setDate("")}>ทุกวัน</button></div><SavedSetTable patientId={id} date={date || undefined} doctor /></>;
}
export function DoctorSession({ patientId, sessionId }: { patientId: string; sessionId: string }) {
  const { profiles, sets } = useDemo(); const patient = profiles.find(p => p.id === patientId)!; const results = sets.filter(s => s.patient_id === patientId && s.session_id === sessionId);
  return <><PageHeading title="รายละเอียดรอบฝึก" subtitle={`${patient.full_name} · ${patient.hn}`} back={`/doctor/patients/${patientId}/assessments`} />{results.length ? <><section className="summary-band"><div><strong>{results.length}</strong><p>เซตที่บันทึก</p></div><div><strong>{results.reduce((sum, s) => sum + s.reps, 0)}</strong><p>ครั้งรวม</p></div><div><strong>{results.reduce((sum, s) => sum + s.elapsed_seconds, 0)}</strong><p>วินาทีที่ฝึก</p></div></section><div className="table-scroll"><table className="data-table"><caption className="sr-only">ผลเซตรอบฝึก</caption><thead><tr><th>เซต</th><th>ท่า</th><th>ครั้ง / เป้าหมาย</th><th>เวลา</th></tr></thead><tbody>{results.map((s, i) => <tr key={s.id}><td>{i + 1}</td><td>{exercises.find(e => e.id === s.exercise_id)!.name}</td><td>{s.reps} / {s.target_reps}</td><td>{s.elapsed_seconds} วินาที</td></tr>)}</tbody></table></div><dl className="data-list"><div><dt>มุมหลัก / คะแนน</dt><dd>ยังไม่มีผลประเมิน AI</dd></div><div><dt>วิดีโอการฝึก</dt><dd>ไม่บันทึกวิดีโอการฝึก</dd></div></dl></> : <EmptyState title="ไม่พบเซตที่บันทึกในรอบนี้" />}</>;
}
